### ISSUE TITLE
Goal Type is not saved

### ISSUE THREAD

**Issue by pmackinney** [treellama/weland#11]
To reproduce:

Launch weland and open a map with >1 polygons
Set the pointer to Place Map Objects
Click in a polygon
(the right-hand side panel shows pull-down menus for Group and Type)
Set the object Group to Goal
Change the Type to something other than 0
Save, quit, reopen
Set the pointer to Select
Click on your Goal object
The Type is 0

**Comment by treellama** [comment]
Pretty sure 304cf2e092ba987deb42925a125b05377e55ab5d fixes this
