### ISSUE TITLE
Removing platform from polygon, then selecting “pave level” crashes Weland

### ISSUE THREAD

**Issue by aaronfreed** [treellama/weland#14]
With the following error:

>Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   at Weland.Level.FixSideType(Side side)
>   at Weland.Level.PaveSide(Side side, Byte collection)
>   at Weland.Level.Pave()
>   at Weland.MapWindow.OnPave(Object o, EventArgs e)

This is on Windows 10, but I suspect it’s probably not OS-exclusive.

**Comment by treellama** [comment]
Can you upload a map that will crash when selecting Pave Level?

**Comment by aaronfreed** [comment]
[The Far Side of Weland Crashes.zip](https://github.com/treellama/weland/files/7178363/The.Far.Side.of.Weland.Crashes.zip)

(In this case I removed the platform at polygon 468.)

It doesn’t seem to happen when I make a new map, place a platform, pave it, remove the platform, and then pave it again. I’m not sure if that’s because my test maps are very small or because I haven’t saved and then reloaded them. That would be a good thing to test.
