### ISSUE TITLE
Weland crashes on start

### ISSUE THREAD

**Issue by kotenok2000** [treellama/weland#18]
Входная строка имела неверный формат.
   в System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   в System.Convert.ToDouble(String value)
   в Weland.MapDrawingArea.LoadColor(String xPath, Color defaultColor)
   в Weland.MapDrawingArea.LoadColors()
   в Weland.MapDrawingArea..ctor()
   в Weland.MapWindow..ctor(String title)
   в Weland.Weland.Main(String[] args)

**Comment by kotenok2000** [comment]
I have . as decimal delimiter.

**Comment by treellama** [comment]
Can you post the contents of your settings.xml? I think in Windows it is in AppData/Local/Weland/settings.xml

**Comment by kotenok2000** [comment]
[settings.xml.txt](https://github.com/treellama/weland/files/10096808/settings.xml.txt)

**Comment by treellama** [comment]
Looks like there is a mismatch between `,` and `.` for writing decimals. For now, you can just edit those by hand and Weland should start up. I will leave this bug open and update it to work cross-culture.
