### ISSUE TITLE
Unhandled Exception when drawing polygons

### ISSUE THREAD

**Issue by ObsidianCarnageX12** [treellama/weland#2]
Every time i draw any shape polygon within the editor i get a blank Unhandled Exception window forcing me to close the program.

Platform : Win 10 Pro x64

**Comment by MavrikRG** [comment]
I'm getting a very similar problem, if I draw polygons it will inevitably show the blank "Unhandled Exception" popup window and close itself.

I run W7 Home Premium 64-bit

**Comment by treellama** [comment]
Some users have reported this happening when running Weland under Mono in Linux. Make sure you're running it under .NET / gtk-sharp for .NET
