### ISSUE TITLE
Can't install on windows 10 machine

### ISSUE THREAD

**Issue by andycorm** [treellama/weland#31]
Hello! I'd love to give Wetland a try, but I can't seem to figure out the instructions on my windows machine. I've installed .NET runtime, GTK# for .NET, and downloaded a copy of the Wetland Github repo, but I cannot find an .exe file to execute.

Is there a missing step I need to complete?

**Comment by treellama** [comment]
You're downloading a release right?

https://github.com/treellama/weland/releases

**Comment by andycorm** [comment]
I was not. Thank you so much!
