### ISSUE TITLE
.exe will not run (Windows 10)

### ISSUE THREAD

**Issue by CrazyEyedMustafa** [treellama/weland#7]
Double-clicking .exe will not do anything. All necessary frameworks and runtimes installed. Unsure of where to go for this issue, so posting here.

**Comment by wjhollyart** [comment]
I'm experiencing the same issue. I'm wondering if it has anything to do with 64-bit compatibility with the GTK# plugin, since my understanding is that the 64-bit version of Mono omits GTK#. Are you running on a 64-bit machine too?

**Comment by Overwatch-C-17** [comment]
Same here, doesn't work on Win 10 64 bit. Editor kinda out of date, been 2 years since latest release.

**Comment by treellama** [comment]
Many people experiencing this issue are trying to run Weland with Mono. I have only tested it with .NET and gtk-sharp for .NET as the README directs. With that combination I confirm it still works with Windows 10.

For additional assistance you can visit the Marathon discord.
