### ISSUE TITLE
The "Levels" menu doesn't initialize correctly when opening unmerged map at 1.4.5

### ISSUE THREAD

**Issue by pfhore-github** [treellama/weland#9]
When I open an unmerged map, It doesn't change the content of the "Levels" menu

Also When I open directly an unmerged map or open it from menu before I view Levels menu, Weland crashed at 

Weland.MapWindow.BuildLevelMenu()

**Comment by pfhore-github** [comment]
Error is NullReferenceException but I don't know where

**Comment by treellama** [comment]
This only happens if I open the map directly (like, `mono Weland.exe /path/to/MyMap.sceA`); it works OK for me to open from the menu.
